# Generated by Django 5.1.7 on 2025-04-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAP', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='userid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
