# Generated by Django 5.1.7 on 2025-04-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAP', '0003_info_userid_info_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
