# Generated by Django 5.1.7 on 2025-04-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAP', '0004_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='old_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='type_contribution',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
