# Generated by Django 5.1.7 on 2025-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAP', '0005_info_old_image_info_type_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('shopType', models.TextField()),
                ('time', models.TextField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('imageURL', models.TextField()),
            ],
        ),
    ]
